// Animated sprites from the atlas generated by tools/sheets/build_sprites.py, ported from js/sprites.js.
import type { Draw2D } from "../../../dotframe/src/draw2d";
import type { Texture } from "../../../dotframe/src/gpu";
import type { Fighter } from "./fighter";
import type { Pose } from "./pose";
import { clamp, DEG, SZ } from "./util";

export const SPR_H = (128 * SZ) / 1.2; // world height of the idle frame

interface Anim {
  name: string;
  f: number[];
  loop: number;
  hit: number;
  flip: boolean;
}

interface CharacterSprites {
  id: string;
  idleH: number;
  // [sx, sy, w, h, anchorX, anchorY]; empty for unused indices.
  frames: number[][];
  anims: Anim[];
}

interface SpriteDataJson {
  characters: CharacterSprites[];
}

interface LoadedCharacter {
  data: CharacterSprites;
  anims: Map<string, Anim>;
}

export interface SpriteFrame {
  anim: string;
  i: number;
}

const characters = new Map<string, LoadedCharacter>();
// Atlas and face textures keyed by character id plus variant ("railly" + "base").
export const atlases = new Map<string, Texture>();
export const faces = new Map<string, Texture>();

export function loadSpriteData(json: string): void {
  const parsed = JSON.parse(json) as SpriteDataJson;
  for (const data of parsed.characters) {
    const anims = new Map<string, Anim>();
    for (const anim of data.anims) anims.set(anim.name, anim);
    characters.set(data.id, { data, anims });
  }
}

export function setAtlas(key: string, texture: Texture, face: boolean): void {
  if (face) faces.set(key, texture);
  else atlases.set(key, texture);
}

function animOf(charId: string, name: string): Anim | null {
  const loaded = characters.get(charId);
  if (!loaded) return null;
  return loaded.anims.get(name) ?? null;
}

const animLength = (charId: string, name: string): number => animOf(charId, name)?.f.length ?? 1;

// Current frame of a fighter for its state.
export function spriteFrame(f: Fighter): SpriteFrame {
  const t = f.game.frame;
  const sf = f.sf;
  const loop = (name: string, speed: number): SpriteFrame => {
    const a = animOf(f.charId, name);
    const step = a && a.loop > 0 ? a.loop : speed > 0 ? speed : 6;
    return { anim: name, i: Math.floor(t / step) % animLength(f.charId, name) };
  };
  const prog = (name: string, p: number): SpriteFrame => {
    const n = animLength(f.charId, name);
    return { anim: name, i: clamp(Math.floor(p * n), 0, n - 1) };
  };
  switch (f.state) {
    case "idle":
    case "respawn":
      return loop("idle", 0);
    case "walk":
      return loop("walk", 0);
    case "dash":
    case "run":
      return loop("run", 0);
    case "turn":
      return prog("land", 0);
    case "crouch":
      return prog("crouch", 0);
    case "jumpsquat":
      return prog("jumpsquat", sf / Math.max(1, f.stats.jumpsquat));
    case "land":
      return prog("land", sf / Math.max(1, f.lag));
    case "air": {
      if (f.djumpT > 0) return prog("djump", (18 - f.djumpT) / 18);
      if (f.vy < -4) return prog("rise", clamp(1 - (-f.vy - 4) / 12, 0, 0.99));
      if (f.vy < 3) return loop("apex", 8);
      return loop("fall", 6);
    }
    case "fall":
      return loop("helpless", 0);
    case "hitstun":
      return !f.ground && f.tumble ? loop("tumble", 0) : prog("hurt", clamp(sf / 12, 0, 0.99));
    case "tumble":
      return loop("tumble", 0);
    case "grabbed":
    case "locked":
      return loop("grabbed", 0);
    case "shield":
    case "shieldstun":
    case "shielddrop":
      return prog("guard", 0);
    case "airdodge":
    case "spotdodge":
      return prog("dodge", sf / 22);
    case "roll":
    case "getroll":
    case "ledgeroll":
    case "tech":
      return prog("roll", sf / 26);
    case "down":
      return prog("down", 0);
    case "getup":
    case "ledgeup":
      return prog("getup", sf / 28);
    case "ledge":
      return loop("ledge", 0);
    case "grabbing":
      return loop("grabhold", 8);
    case "pummel":
      return prog("pummel", sf / 18);
    case "throw":
      return prog(`throw_${f.mv.throwDir === "" ? "f" : f.mv.throwDir}`, sf / 24);
    case "dizzy":
      return f.ground ? loop("dizzy", 0) : loop("tumble", 0);
    case "attack":
      return moveFrame(f);
  }
  return loop("idle", 0);
}

const MOVE_FALLBACK = new Map<string, string>([
  ["jab2", "jab"],
  ["dashgrab", "grab"],
  ["counterHit", "nspecial"],
]);

function moveFrame(f: Fighter): SpriteFrame {
  const m = f.move;
  if (!m) return { anim: "idle", i: 0 };
  const sf = f.sf;
  const id = m.id;
  const t = f.game.frame;
  const rail = f.charId === "railly";
  const anth = f.charId === "anthony";
  if (rail && id === "uspecial") {
    if (sf <= 42) return { anim: "uspecial", i: 0 };
    if (sf <= 70) return { anim: "uspecial", i: 1 + (Math.floor((sf - 43) / 4) % 4) };
    return { anim: "uspecial", i: 5 };
  }
  if (rail && id === "sspecial") return { anim: "sspecial", i: sf <= 10 ? 0 : sf <= 22 ? 1 + (sf % 4 < 2 ? 0 : 1) : 3 };
  if (rail && id === "dspecial") return { anim: "dspecial", i: Math.floor(t / 4) % 2 };
  if (rail && id === "final") {
    const mv = f.mv;
    if (mv.caught) {
      return mv.ct >= 76
        ? { anim: "finalend", i: Math.min(2, Math.floor((mv.ct - 76) / 5)) }
        : { anim: "finalcombo", i: Math.floor(t / 3) % 4 };
    }
    if (sf <= 16) return { anim: "final", i: Math.min(7, Math.floor(sf / 2)) };
    return { anim: "dashattack", i: 1 };
  }
  if (anth && id === "dsmash") {
    return sf < 6 ? { anim: "crouch", i: 0 } : { anim: "pushups", i: ((((sf - 8) % 12) + 12) % 12) < 6 ? 1 : 0 };
  }
  if (anth && id === "uspecial") {
    return sf <= 5
      ? { anim: "crouch", i: 0 }
      : sf <= 36
        ? { anim: "uspecial", i: Math.floor(t / 3) % 4 }
        : { anim: "helpless", i: Math.floor(t / 8) % 2 };
  }
  if (anth && id === "nspecial") return { anim: "nspecial", i: sf < 9 ? 0 : f.chargeFlash ? 1 : sf < 16 ? 2 : 3 };
  if (anth && id === "dspecial") return { anim: "dspecial", i: Math.floor(t / 6) % 2 };
  if (anth && id === "final") {
    return sf >= 108 && sf < 125 ? { anim: "finalflash", i: sf < 116 ? 0 : 1 } : { anim: "final", i: Math.floor(t / 10) % 2 };
  }
  let name = id;
  if (!animOf(f.charId, name)) name = MOVE_FALLBACK.get(id) ?? "jab";
  const a = animOf(f.charId, name);
  if (!a) return { anim: "idle", i: 0 };
  const n = a.f.length;
  if (a.loop > 0 && a.hit < 0) return { anim: name, i: Math.floor(t / a.loop) % n };
  const h = a.hit >= 0 ? a.hit : Math.floor(n / 2);
  let i = 0;
  if (m.charge && f.chargeT > 0 && sf === m.charge) i = Math.max(0, h - 1);
  else if (sf < m.as) i = h ? Math.min(h - 1, Math.floor((sf / m.as) * h)) : 0;
  else if (sf <= m.ae + 1) i = h;
  else i = Math.min(n - 1, h + 1 + Math.floor(((sf - m.ae - 1) / Math.max(1, m.frames - m.ae)) * (n - h - 1)));
  return { anim: name, i };
}

// Draws the fighter's sprite in world space. silhouette: a color to draw the frame as a solid shape, or "".
export function drawSpriteWorld(
  ctx: Draw2D,
  f: Fighter,
  pose: Pose,
  x: number,
  y: number,
  facing: number,
  alpha: number,
  silhouette: string,
): void {
  const loaded = characters.get(f.charId);
  if (!loaded) return;
  const D = loaded.data;
  const animName = pose.sprAnim !== "" ? pose.sprAnim : "tumble";
  const index = pose.sprAnim !== "" ? pose.sprIndex : Math.floor(f.game.frame / 4) % 4;
  const a = loaded.anims.get(animName) ?? loaded.anims.get("idle");
  if (!a) return;
  const fr = D.frames[a.f[Math.min(index, a.f.length - 1)]];
  if (!fr || fr.length < 6) return;
  const atlas = atlases.get(f.charId + f.variant);
  if (!atlas) return;
  const sx = fr[0];
  const sy = fr[1];
  const w = fr[2];
  const h = fr[3];
  const ax = fr[4];
  const ay = fr[5];
  const sc = SPR_H / D.idleH;
  ctx.save();
  ctx.setGlobalAlpha(ctx.getGlobalAlpha() * alpha);
  ctx.translate(Math.round(x), Math.round(y));
  const rot = pose.sprRot;
  if (rot) {
    ctx.translate(0, -62 * SZ);
    ctx.rotate(rot * DEG * facing);
    ctx.translate(0, 62 * SZ);
  }
  ctx.scale(facing * (a.flip ? -1 : 1) * sc, sc);
  if (silhouette !== "") ctx.drawImageTinted(atlas, sx, sy, w, h, -ax, -ay, w, h, silhouette);
  else ctx.drawImage(atlas, sx, sy, w, h, -ax, -ay, w, h);
  ctx.restore();
}

export function drawFighterBody(
  ctx: Draw2D,
  f: Fighter,
  pose: Pose,
  x: number,
  y: number,
  facing: number,
  alpha: number,
  silhouette: string,
): void {
  drawSpriteWorld(ctx, f, pose, x, y, facing, alpha, silhouette);
}
