// Decodes the base64 MP3s embedded in js/sfxdata.js into port/assets/sfx/<name>.mp3.
const fs = require("fs");
const path = require("path");
const vm = require("vm");
const ctx = {};
vm.createContext(ctx);
vm.runInContext(fs.readFileSync(path.join(__dirname, "..", "..", "js", "sfxdata.js"), "utf8") + ";globalThis.__S = SFX_DATA;", ctx);
const out = path.join(__dirname, "..", "assets", "sfx");
fs.mkdirSync(out, { recursive: true });
const names = Object.keys(ctx.__S);
for (const name of names) {
  const url = ctx.__S[name];
  fs.writeFileSync(path.join(out, `${name}.mp3`), Buffer.from(url.slice(url.indexOf(",") + 1), "base64"));
}
fs.writeFileSync(path.join(__dirname, "..", "src", "sfx-names.ts"), `// Generated by tools/extract-sfx.cjs.\nexport const SFX_NAMES: string[] = ${JSON.stringify(names)};\n`);
console.log(`${names.length} sounds`);
